import { useAppKernel } from './useAppKernel'
import { useBackgroundTasks } from './useBackgroundTasks'
import { useGenerationTasks } from './useGenerationTasks'
import { useAccessSession } from './useAccessSession'
import { useAppLifecycle } from './useAppLifecycle'
import { useAppSettings } from './useAppSettings'
import { useGenerateComposer } from './useGenerateComposer'
import { useHistoryHub } from './useHistoryHub'
import { useTaskActions } from './useTaskActions'
import { useWorksHub } from './useWorksHub'
import { getImageSize } from '../lib/ratios'

export function useAppDataFlow() {
  const {
    settings,
    settingsOpen,
    ratio,
    resolution,
    setSettingsOpen,
    setRatio,
    setResolution,
    updateSettings,
    patchSettings,
  } = useAppSettings()
  const {
    message,
    setMessage,
    showMessage,
    clearMessage,
    adminOpen,
    setAdminOpen,
    getAccessPassword,
  } = useAppKernel(settings.accessPassword)
  const {
    history,
    historyCollapsed,
    refreshHistory,
    saveCloudTaskToHistory,
    handleDeleteHistory,
    handleClearHistory,
    toggleHistoryCollapsed,
  } = useHistoryHub()
  const {
    me,
    unlocked,
    unlocking,
    handleUnlock,
    handleAccessPasswordUpdated,
    refreshCurrentUser,
    handleLogin: loginWithSession,
    handleRegister: registerWithSession,
    handleLogout: logoutWithSession,
  } = useAccessSession({
    accessPassword: settings.accessPassword,
    getAccessPassword,
    showMessage,
    onAccessPasswordUpdated: (nextPassword) => patchSettings({ accessPassword: nextPassword }),
  })
  const {
    tasks,
    setTasks,
    runGenerationTask,
    handleUploadImage,
    removeTask,
    clearFinishedTasks,
  } = useGenerationTasks({
    showMessage,
    getAccessPassword,
    onOpenSettings: () => setSettingsOpen(true),
    onHistoryRefresh: refreshHistory,
  })
  const {
    works,
    worksLoading,
    workSort,
    workOffset,
    workTotal,
    myWorks,
    myWorksLoading,
    favoriteWorks,
    favoriteWorksLoading,
    activeCommentWork,
    workComments,
    workCommentsLoading,
    workCommentsTotal,
    profileUserId,
    profileData,
    profileWorks,
    profileLoading,
    resetForLock,
    resetForNoUser,
    closeComments,
    closeProfile,
    refreshWorks,
    refreshMyWorks,
    refreshMyFavorites,
    refreshWorkComments,
    refreshProfile,
    handleToggleLike,
    handleToggleFavorite,
    handleOpenComments,
    handleCreateComment,
    handleDeleteComment,
    handleOpenUserProfile,
    handleDeleteMyWork,
    handleChangeWorkSort,
    handleChangeWorkPage,
    handleRefreshSquare,
  } = useWorksHub({ me, getAccessPassword, showMessage })
  const size = getImageSize(ratio, resolution)
  const {
    backgroundStats,
    syncingCloudTasks,
    applyCloudTask,
    restoreActiveBackgroundTasks,
    syncCloudTasks,
  } = useBackgroundTasks({
    getAccessPassword,
    showMessage,
    setTasks,
    onSaveCloudTaskToHistory: saveCloudTaskToHistory,
    onMissingAccessPassword: () => setSettingsOpen(true),
  })
  const {
    mode,
    setMode,
    prompt,
    setPrompt,
    inputImages,
    setInputImages,
    handleGenerate,
    handleUseAsReference,
    reusePrompt,
  } = useGenerateComposer({
    settings,
    ratio,
    resolution,
    size,
    updateSettings,
    getAccessPassword,
    showMessage,
    clearMessage,
    onOpenSettings: () => setSettingsOpen(true),
    setTasks,
    runGenerationTask,
    applyCloudTask,
  })
  const {
    handlePublishWork,
    handleRetryBackgroundTask,
    handleShowHistoryInResults,
  } = useTaskActions({
    me,
    tasks,
    setTasks,
    settings,
    getAccessPassword,
    showMessage,
    onOpenSettings: () => setSettingsOpen(true),
    applyCloudTask,
    refreshWorks,
    refreshMyWorks,
  })
  useAppLifecycle({
    accessPassword: settings.accessPassword,
    unlocked,
    meId: me?.id,
    profileUserId,
    workSort,
    workOffset,
    restoreActiveBackgroundTasks,
    resetForLock,
    resetForNoUser,
    refreshCurrentUser,
    refreshWorks,
    refreshMyWorks,
    refreshMyFavorites,
    refreshProfile,
  })

  return {
    app: {
      unlocked,
      unlocking,
      accessPassword: settings.accessPassword,
      handleUnlock,
      message,
      setMessage,
      showMessage,
      adminOpen,
      setAdminOpen,
    },
    settings: {
      settings,
      settingsOpen,
      ratio,
      resolution,
      setSettingsOpen,
      setRatio,
      setResolution,
      updateSettings,
      patchSettings,
    },
    auth: {
      me,
      worksLoading,
      handleAccessPasswordUpdated,
      loginWithSession,
      registerWithSession,
      logoutWithSession,
      refreshWorks,
      resetForLock,
    },
    generation: {
      mode,
      setMode,
      prompt,
      setPrompt,
      inputImages,
      setInputImages,
      size,
      handleGenerate,
      handleUseAsReference,
      reusePrompt,
    },
    workspace: {
      works,
      myWorks,
      favoriteWorks,
      myWorksLoading,
      favoriteWorksLoading,
      workSort,
      workOffset,
      workTotal,
      handleRefreshSquare,
      handleChangeWorkSort,
      handleChangeWorkPage,
      handleToggleLike,
      handleToggleFavorite,
      handleOpenComments,
      handleOpenUserProfile,
      handleDeleteMyWork,
    },
    tasks: {
      tasks,
      handleUploadImage,
      removeTask,
      clearFinishedTasks,
      syncCloudTasks,
      backgroundStats,
      syncingCloudTasks,
      handlePublishWork,
      handleRetryBackgroundTask,
    },
    history: {
      history,
      historyCollapsed,
      toggleHistoryCollapsed,
      handleDeleteHistory,
      handleClearHistory,
      handleShowHistoryInResults,
      reusePrompt,
      handleUseAsReference,
    },
    comments: {
      activeCommentWork,
      workComments,
      workCommentsTotal,
      workCommentsLoading,
      closeComments,
      refreshWorkComments,
      handleCreateComment,
      handleDeleteComment,
    },
    profile: {
      profileUserId,
      profileData,
      profileWorks,
      profileLoading,
      closeProfile,
    },
  }
}

export type AppDataFlow = ReturnType<typeof useAppDataFlow>
